# @package _global_

model_name: Gemma_3_1B_Instruct

module:
  _target_: recipe.models.${model_name}
  temperature: 0.8
  top_p: 0.95

  max_tokens: 4000
  convert_prompt_to_chat: True
  tensor_parallel_size: 1
  max_model_len: 32768
  enforce_eager: True