# @package _global_

model_name: Llama3_1_8B_Instruct

module:
  _target_: recipe.models.${model_name}
  local_model_path: null
  temperature: 0.8
  top_p: 0.95

  max_tokens: 4000
  convert_prompt_to_chat: True
  tensor_parallel_size: 1
  max_model_len: 32768   #Â Context window
  use_system_prompt: False